// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Project struct {
	ID          uint64       `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Color       string       `json:"color"`
	SortOrder   float64      `json:"sort_order"`
	ArchivedAt  sql.NullTime `json:"archived_at"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type Task struct {
	ID          uint64       `json:"id"`
	ProjectID   uint64       `json:"project_id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Status      string       `json:"status"`
	Priority    string       `json:"priority"`
	DueDate     sql.NullTime `json:"due_date"`
	StartDate   sql.NullTime `json:"start_date"`
	CompletedAt sql.NullTime `json:"completed_at"`
	Locked      bool         `json:"locked"`
	SortOrder   float64      `json:"sort_order"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type TaskWorkDay struct {
	TaskID    uint64    `json:"task_id"`
	WorkDate  time.Time `json:"work_date"`
	Note      string    `json:"note"`
	CreatedAt time.Time `json:"created_at"`
}
