// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createProject = `-- name: CreateProject :execrows
INSERT INTO projects (name, description, color, sort_order)
VALUES (?, ?, ?, ?)
`

type CreateProjectParams struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Color       string  `json:"color"`
	SortOrder   float64 `json:"sort_order"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT
    p.id,
    p.name,
    p.description,
    p.color,
    p.sort_order,
    p.archived_at,
    p.created_at
FROM projects p
WHERE p.id = ?
`

type GetProjectRow struct {
	ID          uint64       `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Color       string       `json:"color"`
	SortOrder   float64      `json:"sort_order"`
	ArchivedAt  sql.NullTime `json:"archived_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

func (q *Queries) GetProject(ctx context.Context, id uint64) (GetProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const lastInsertID = `-- name: LastInsertID :one
SELECT LAST_INSERT_ID() AS id
`

func (q *Queries) LastInsertID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastInsertID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id,
    p.name,
    p.description,
    p.color,
    p.sort_order,
    p.archived_at,
    p.created_at,
    COALESCE(t.task_count, 0) AS task_count,
    CAST(COALESCE(t.open_count, 0) AS SIGNED) AS open_count
FROM projects p
LEFT JOIN (
    SELECT
        project_id,
        COUNT(*) AS task_count,
        CAST(COALESCE(SUM(CASE WHEN status <> 'done' THEN 1 ELSE 0 END), 0) AS SIGNED) AS open_count
    FROM tasks
    GROUP BY project_id
) t ON t.project_id = p.id
CROSS JOIN (SELECT CAST(? AS UNSIGNED) AS f_archived) f
WHERE (f.f_archived = 1 OR p.archived_at IS NULL)
ORDER BY p.sort_order ASC, p.id ASC
`

type ListProjectsRow struct {
	ID          uint64       `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Color       string       `json:"color"`
	SortOrder   float64      `json:"sort_order"`
	ArchivedAt  sql.NullTime `json:"archived_at"`
	CreatedAt   time.Time    `json:"created_at"`
	TaskCount   int64        `json:"task_count"`
	OpenCount   int64        `json:"open_count"`
}

func (q *Queries) ListProjects(ctx context.Context, includeArchived int64) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.TaskCount,
			&i.OpenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectArchived = `-- name: SetProjectArchived :execrows
UPDATE projects SET archived_at = ? WHERE id = ?
`

type SetProjectArchivedParams struct {
	ArchivedAt sql.NullTime `json:"archived_at"`
	ID         uint64       `json:"id"`
}

func (q *Queries) SetProjectArchived(ctx context.Context, arg SetProjectArchivedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProjectArchived, arg.ArchivedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProjectSort = `-- name: SetProjectSort :exec
UPDATE projects SET sort_order = ? WHERE id = ?
`

type SetProjectSortParams struct {
	SortOrder float64 `json:"sort_order"`
	ID        uint64  `json:"id"`
}

func (q *Queries) SetProjectSort(ctx context.Context, arg SetProjectSortParams) error {
	_, err := q.db.ExecContext(ctx, setProjectSort, arg.SortOrder, arg.ID)
	return err
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE projects
SET name        = ?,
    description = ?,
    color       = ?
WHERE id = ?
`

type UpdateProjectParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Color       string `json:"color"`
	ID          uint64 `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
