// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddWorkDay(ctx context.Context, arg AddWorkDayParams) (int64, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (int64, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error)
	DeleteProject(ctx context.Context, id uint64) error
	DeleteTask(ctx context.Context, id uint64) error
	GetProject(ctx context.Context, id uint64) (GetProjectRow, error)
	GetTask(ctx context.Context, id uint64) (GetTaskRow, error)
	LastInsertID(ctx context.Context) (int64, error)
	ListBoardTasks(ctx context.Context, arg ListBoardTasksParams) ([]ListBoardTasksRow, error)
	ListCalendarEntries(ctx context.Context, arg ListCalendarEntriesParams) ([]ListCalendarEntriesRow, error)
	ListProjects(ctx context.Context, includeArchived int64) ([]ListProjectsRow, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error)
	ListWorkDays(ctx context.Context, taskID uint64) ([]ListWorkDaysRow, error)
	ListWorkDaysForTasks(ctx context.Context, taskIds []uint64) ([]ListWorkDaysForTasksRow, error)
	RemoveWorkDay(ctx context.Context, arg RemoveWorkDayParams) error
	SetProjectArchived(ctx context.Context, arg SetProjectArchivedParams) (int64, error)
	SetProjectSort(ctx context.Context, arg SetProjectSortParams) error
	SetTaskLocked(ctx context.Context, arg SetTaskLockedParams) (int64, error)
	SetTaskSort(ctx context.Context, arg SetTaskSortParams) error
	SetTaskStart(ctx context.Context, arg SetTaskStartParams) (int64, error)
	SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (int64, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
