// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const addWorkDay = `-- name: AddWorkDay :execrows
INSERT INTO task_work_days (task_id, work_date, note)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE note = VALUES(note)
`

type AddWorkDayParams struct {
	TaskID   uint64    `json:"task_id"`
	WorkDate time.Time `json:"work_date"`
	Note     string    `json:"note"`
}

func (q *Queries) AddWorkDay(ctx context.Context, arg AddWorkDayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addWorkDay, arg.TaskID, arg.WorkDate, arg.Note)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createTask = `-- name: CreateTask :execrows
INSERT INTO tasks (project_id, title, description, status, priority, due_date, sort_order)
VALUES (
    ?,
    ?,
    ?,
    CAST(?   AS CHAR(16)),
    CAST(? AS CHAR(16)),
    ?,
    ?
)
`

type CreateTaskParams struct {
	ProjectID   uint64       `json:"project_id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Status      interface{}  `json:"status"`
	Priority    interface{}  `json:"priority"`
	DueDate     sql.NullTime `json:"due_date"`
	SortOrder   float64      `json:"sort_order"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT
    t.id,
    t.project_id,
    t.title,
    t.description,
    t.status,
    t.priority,
    t.due_date,
    t.start_date,
    t.completed_at,
    t.locked,
    t.sort_order,
    t.created_at,
    t.updated_at,
    p.name AS project_name,
    p.color AS project_color
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.id = ?
`

type GetTaskRow struct {
	ID           uint64       `json:"id"`
	ProjectID    uint64       `json:"project_id"`
	Title        string       `json:"title"`
	Description  string       `json:"description"`
	Status       string       `json:"status"`
	Priority     string       `json:"priority"`
	DueDate      sql.NullTime `json:"due_date"`
	StartDate    sql.NullTime `json:"start_date"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	Locked       bool         `json:"locked"`
	SortOrder    float64      `json:"sort_order"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	ProjectName  string       `json:"project_name"`
	ProjectColor string       `json:"project_color"`
}

func (q *Queries) GetTask(ctx context.Context, id uint64) (GetTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.StartDate,
		&i.CompletedAt,
		&i.Locked,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectName,
		&i.ProjectColor,
	)
	return i, err
}

const listBoardTasks = `-- name: ListBoardTasks :many
SELECT
    t.id,
    t.project_id,
    t.title,
    t.description,
    t.status,
    t.priority,
    t.due_date,
    t.start_date,
    t.completed_at,
    t.locked,
    t.sort_order,
    t.created_at,
    t.updated_at,
    COALESCE(w.work_days, 0) AS work_day_count
FROM tasks t
LEFT JOIN (
    SELECT task_id, COUNT(*) AS work_days FROM task_work_days GROUP BY task_id
) w ON w.task_id = t.id
CROSS JOIN (
    SELECT
        CAST(?   AS CHAR(16))  AS f_status,
        CAST(? AS CHAR(16)) AS f_priority,
        CAST(?      AS CHAR(16))  AS f_due,
        CAST(?        AS CHAR(255)) AS f_q
) f
WHERE t.project_id = ?
  AND (f.f_status = '' OR t.status = f.f_status)
  AND (f.f_priority = '' OR t.priority = f.f_priority)
  AND (f.f_q = '' OR t.title LIKE CONCAT('%', f.f_q, '%'))
  AND (f.f_due = '' OR (
        (f.f_due = 'overdue' AND t.due_date IS NOT NULL AND t.due_date < CURDATE() AND t.status <> 'done')
     OR (f.f_due = 'week' AND t.due_date IS NOT NULL AND t.due_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 7 DAY))
     OR (f.f_due = 'none' AND t.due_date IS NULL)
  ))
ORDER BY t.sort_order ASC, t.id ASC
`

type ListBoardTasksParams struct {
	Status    interface{} `json:"status"`
	Priority  interface{} `json:"priority"`
	Due       interface{} `json:"due"`
	Q         interface{} `json:"q"`
	ProjectID uint64      `json:"project_id"`
}

type ListBoardTasksRow struct {
	ID           uint64       `json:"id"`
	ProjectID    uint64       `json:"project_id"`
	Title        string       `json:"title"`
	Description  string       `json:"description"`
	Status       string       `json:"status"`
	Priority     string       `json:"priority"`
	DueDate      sql.NullTime `json:"due_date"`
	StartDate    sql.NullTime `json:"start_date"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	Locked       bool         `json:"locked"`
	SortOrder    float64      `json:"sort_order"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	WorkDayCount int64        `json:"work_day_count"`
}

func (q *Queries) ListBoardTasks(ctx context.Context, arg ListBoardTasksParams) ([]ListBoardTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBoardTasks,
		arg.Status,
		arg.Priority,
		arg.Due,
		arg.Q,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardTasksRow{}
	for rows.Next() {
		var i ListBoardTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.StartDate,
			&i.CompletedAt,
			&i.Locked,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkDayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarDueEntries = `-- name: ListCalendarDueEntries :many
SELECT
    t.due_date,
    t.id AS task_id,
    t.title,
    t.status,
    t.priority,
    t.locked,
    t.project_id,
    p.name AS project_name,
    p.color AS project_color
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.due_date BETWEEN ? AND ?
  AND FIND_IN_SET(t.project_id, COALESCE(NULLIF(?, ''), CAST(t.project_id AS CHAR)))
  AND t.status = COALESCE(?, t.status)
  AND t.priority = COALESCE(?, t.priority)
  AND CONCAT_WS(' ', t.title, t.description) LIKE CONCAT('%', COALESCE(?, ''), '%')
ORDER BY t.due_date ASC, t.id ASC
`

type ListCalendarDueEntriesParams struct {
	FromDate   sql.NullTime   `json:"from_date"`
	ToDate     sql.NullTime   `json:"to_date"`
	ProjectIds interface{}    `json:"project_ids"`
	Status     sql.NullString `json:"status"`
	Priority   sql.NullString `json:"priority"`
	Q          interface{}    `json:"q"`
}

type ListCalendarDueEntriesRow struct {
	DueDate      sql.NullTime `json:"due_date"`
	TaskID       uint64       `json:"task_id"`
	Title        string       `json:"title"`
	Status       string       `json:"status"`
	Priority     string       `json:"priority"`
	Locked       bool         `json:"locked"`
	ProjectID    uint64       `json:"project_id"`
	ProjectName  string       `json:"project_name"`
	ProjectColor string       `json:"project_color"`
}

func (q *Queries) ListCalendarDueEntries(ctx context.Context, arg ListCalendarDueEntriesParams) ([]ListCalendarDueEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarDueEntries,
		arg.FromDate,
		arg.ToDate,
		arg.ProjectIds,
		arg.Status,
		arg.Priority,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarDueEntriesRow{}
	for rows.Next() {
		var i ListCalendarDueEntriesRow
		if err := rows.Scan(
			&i.DueDate,
			&i.TaskID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Locked,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarEntries = `-- name: ListCalendarEntries :many

SELECT
    w.work_date,
    t.id AS task_id,
    t.title,
    t.status,
    t.priority,
    t.locked,
    t.project_id,
    p.name AS project_name,
    p.color AS project_color
FROM task_work_days w
JOIN tasks t ON t.id = w.task_id
JOIN projects p ON p.id = t.project_id
WHERE w.work_date BETWEEN ? AND ?
  AND FIND_IN_SET(t.project_id, COALESCE(NULLIF(?, ''), CAST(t.project_id AS CHAR)))
  AND t.status = COALESCE(?, t.status)
  AND t.priority = COALESCE(?, t.priority)
  AND CONCAT_WS(' ', t.title, t.description) LIKE CONCAT('%', COALESCE(?, ''), '%')
ORDER BY w.work_date ASC, t.id ASC
`

type ListCalendarEntriesParams struct {
	FromDate   time.Time      `json:"from_date"`
	ToDate     time.Time      `json:"to_date"`
	ProjectIds interface{}    `json:"project_ids"`
	Status     sql.NullString `json:"status"`
	Priority   sql.NullString `json:"priority"`
	Q          interface{}    `json:"q"`
}

type ListCalendarEntriesRow struct {
	WorkDate     time.Time `json:"work_date"`
	TaskID       uint64    `json:"task_id"`
	Title        string    `json:"title"`
	Status       string    `json:"status"`
	Priority     string    `json:"priority"`
	Locked       bool      `json:"locked"`
	ProjectID    uint64    `json:"project_id"`
	ProjectName  string    `json:"project_name"`
	ProjectColor string    `json:"project_color"`
}

// Filter style note: each optional filter is referenced exactly once by
// folding the "no filter" case into a COALESCE/NULLIF default. Repeating the
// same argument in two places makes sqlc infer conflicting types and drop it.
func (q *Queries) ListCalendarEntries(ctx context.Context, arg ListCalendarEntriesParams) ([]ListCalendarEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarEntries,
		arg.FromDate,
		arg.ToDate,
		arg.ProjectIds,
		arg.Status,
		arg.Priority,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarEntriesRow{}
	for rows.Next() {
		var i ListCalendarEntriesRow
		if err := rows.Scan(
			&i.WorkDate,
			&i.TaskID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Locked,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportTasks = `-- name: ListExportTasks :many

SELECT
    t.id,
    p.name AS project_name,
    t.title,
    t.description,
    t.status,
    t.priority,
    t.due_date,
    t.start_date,
    t.completed_at,
    t.locked,
    t.created_at,
    COALESCE(all_days.days, 0) AS total_work_days,
    all_days.list AS work_day_list
FROM tasks t
JOIN projects p ON p.id = t.project_id
LEFT JOIN (
    SELECT
        task_id,
        COUNT(*) AS days,
        GROUP_CONCAT(work_date ORDER BY work_date SEPARATOR ' ') AS list
    FROM task_work_days
    GROUP BY task_id
) all_days ON all_days.task_id = t.id
WHERE FIND_IN_SET(t.project_id, COALESCE(NULLIF(?, ''), CAST(t.project_id AS CHAR)))
  AND t.status = COALESCE(?, t.status)
  AND t.priority = COALESCE(?, t.priority)
ORDER BY p.sort_order ASC, FIELD(t.status, 'todo', 'ongoing', 'done'), t.sort_order ASC, t.id ASC
`

type ListExportTasksParams struct {
	ProjectIds interface{}    `json:"project_ids"`
	Status     sql.NullString `json:"status"`
	Priority   sql.NullString `json:"priority"`
}

type ListExportTasksRow struct {
	ID            uint64         `json:"id"`
	ProjectName   string         `json:"project_name"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	Status        string         `json:"status"`
	Priority      string         `json:"priority"`
	DueDate       sql.NullTime   `json:"due_date"`
	StartDate     sql.NullTime   `json:"start_date"`
	CompletedAt   sql.NullTime   `json:"completed_at"`
	Locked        bool           `json:"locked"`
	CreatedAt     time.Time      `json:"created_at"`
	TotalWorkDays int64          `json:"total_work_days"`
	WorkDayList   sql.NullString `json:"work_day_list"`
}

// Export pulls every task for the selected projects along with its full work-day
// list; the date range is applied in Go. Keeping the range out of the SQL avoids
// repeating the same bound parameter in several places.
func (q *Queries) ListExportTasks(ctx context.Context, arg ListExportTasksParams) ([]ListExportTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listExportTasks, arg.ProjectIds, arg.Status, arg.Priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExportTasksRow{}
	for rows.Next() {
		var i ListExportTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.StartDate,
			&i.CompletedAt,
			&i.Locked,
			&i.CreatedAt,
			&i.TotalWorkDays,
			&i.WorkDayList,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT
    t.id,
    t.project_id,
    t.title,
    t.description,
    t.status,
    t.priority,
    t.due_date,
    t.start_date,
    t.completed_at,
    t.locked,
    t.sort_order,
    t.created_at,
    t.updated_at,
    p.name AS project_name,
    p.color AS project_color,
    COALESCE(w.work_days, 0) AS work_day_count
FROM tasks t
JOIN projects p ON p.id = t.project_id
LEFT JOIN (
    SELECT task_id, COUNT(*) AS work_days FROM task_work_days GROUP BY task_id
) w ON w.task_id = t.id
CROSS JOIN (
    SELECT
        CAST(? AS CHAR(64)) AS f_project_ids,
        CAST(?      AS CHAR(16))  AS f_status,
        CAST(?    AS CHAR(16))  AS f_priority,
        CAST(?         AS CHAR(16))  AS f_due,
        CAST(?           AS CHAR(255)) AS f_q
) f
WHERE (f.f_project_ids = '' OR FIND_IN_SET(t.project_id, f.f_project_ids))
  AND (f.f_status = '' OR t.status = f.f_status)
  AND (f.f_priority = '' OR t.priority = f.f_priority)
  AND (f.f_q = '' OR t.title LIKE CONCAT('%', f.f_q, '%') OR t.description LIKE CONCAT('%', f.f_q, '%'))
  AND (f.f_due = '' OR (
        (f.f_due = 'overdue' AND t.due_date IS NOT NULL AND t.due_date < CURDATE() AND t.status <> 'done')
     OR (f.f_due = 'week' AND t.due_date IS NOT NULL AND t.due_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 7 DAY))
     OR (f.f_due = 'none' AND t.due_date IS NULL)
  ))
ORDER BY t.updated_at DESC, t.id DESC
`

type ListTasksParams struct {
	ProjectIds interface{} `json:"project_ids"`
	Status     interface{} `json:"status"`
	Priority   interface{} `json:"priority"`
	Due        interface{} `json:"due"`
	Q          interface{} `json:"q"`
}

type ListTasksRow struct {
	ID           uint64       `json:"id"`
	ProjectID    uint64       `json:"project_id"`
	Title        string       `json:"title"`
	Description  string       `json:"description"`
	Status       string       `json:"status"`
	Priority     string       `json:"priority"`
	DueDate      sql.NullTime `json:"due_date"`
	StartDate    sql.NullTime `json:"start_date"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	Locked       bool         `json:"locked"`
	SortOrder    float64      `json:"sort_order"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	ProjectName  string       `json:"project_name"`
	ProjectColor string       `json:"project_color"`
	WorkDayCount int64        `json:"work_day_count"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.ProjectIds,
		arg.Status,
		arg.Priority,
		arg.Due,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.StartDate,
			&i.CompletedAt,
			&i.Locked,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.ProjectColor,
			&i.WorkDayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkDays = `-- name: ListWorkDays :many
SELECT work_date, note FROM task_work_days
WHERE task_id = ?
ORDER BY work_date ASC
`

type ListWorkDaysRow struct {
	WorkDate time.Time `json:"work_date"`
	Note     string    `json:"note"`
}

func (q *Queries) ListWorkDays(ctx context.Context, taskID uint64) ([]ListWorkDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkDays, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkDaysRow{}
	for rows.Next() {
		var i ListWorkDaysRow
		if err := rows.Scan(&i.WorkDate, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkDaysForTasks = `-- name: ListWorkDaysForTasks :many
SELECT task_id, work_date FROM task_work_days
WHERE task_id IN (/*SLICE:task_ids*/?)
ORDER BY work_date ASC
`

type ListWorkDaysForTasksRow struct {
	TaskID   uint64    `json:"task_id"`
	WorkDate time.Time `json:"work_date"`
}

func (q *Queries) ListWorkDaysForTasks(ctx context.Context, taskIds []uint64) ([]ListWorkDaysForTasksRow, error) {
	query := listWorkDaysForTasks
	var queryParams []interface{}
	if len(taskIds) > 0 {
		for _, v := range taskIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:task_ids*/?", strings.Repeat(",?", len(taskIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:task_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkDaysForTasksRow{}
	for rows.Next() {
		var i ListWorkDaysForTasksRow
		if err := rows.Scan(&i.TaskID, &i.WorkDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkDay = `-- name: RemoveWorkDay :exec
DELETE FROM task_work_days WHERE task_id = ? AND work_date = ?
`

type RemoveWorkDayParams struct {
	TaskID   uint64    `json:"task_id"`
	WorkDate time.Time `json:"work_date"`
}

func (q *Queries) RemoveWorkDay(ctx context.Context, arg RemoveWorkDayParams) error {
	_, err := q.db.ExecContext(ctx, removeWorkDay, arg.TaskID, arg.WorkDate)
	return err
}

const setTaskLocked = `-- name: SetTaskLocked :execrows
UPDATE tasks SET locked = ? WHERE id = ?
`

type SetTaskLockedParams struct {
	Locked bool   `json:"locked"`
	ID     uint64 `json:"id"`
}

func (q *Queries) SetTaskLocked(ctx context.Context, arg SetTaskLockedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskLocked, arg.Locked, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTaskSort = `-- name: SetTaskSort :exec
UPDATE tasks SET sort_order = ? WHERE id = ?
`

type SetTaskSortParams struct {
	SortOrder float64 `json:"sort_order"`
	ID        uint64  `json:"id"`
}

func (q *Queries) SetTaskSort(ctx context.Context, arg SetTaskSortParams) error {
	_, err := q.db.ExecContext(ctx, setTaskSort, arg.SortOrder, arg.ID)
	return err
}

const setTaskStart = `-- name: SetTaskStart :execrows
UPDATE tasks
SET status     = 'ongoing',
    start_date = ?,
    locked     = FALSE
WHERE id = ?
`

type SetTaskStartParams struct {
	StartDate sql.NullTime `json:"start_date"`
	ID        uint64       `json:"id"`
}

func (q *Queries) SetTaskStart(ctx context.Context, arg SetTaskStartParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskStart, arg.StartDate, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTaskStatus = `-- name: SetTaskStatus :execrows
UPDATE tasks t
JOIN (SELECT CAST(? AS CHAR(16)) AS s) f ON TRUE
SET t.status       = f.s,
    t.start_date   = CASE WHEN f.s = 'todo'  THEN NULL ELSE t.start_date END,
    t.completed_at = CASE WHEN f.s = 'done'  THEN CURRENT_TIMESTAMP ELSE NULL END,
    t.locked       = CASE WHEN f.s = 'done'  THEN TRUE ELSE FALSE END
WHERE t.id = ?
`

type SetTaskStatusParams struct {
	Status interface{} `json:"status"`
	ID     uint64      `json:"id"`
}

func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTask = `-- name: UpdateTask :execrows
UPDATE tasks
SET title       = ?,
    description = ?,
    priority    = CAST(? AS CHAR(16)),
    due_date    = ?
WHERE id = ?
`

type UpdateTaskParams struct {
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Priority    interface{}  `json:"priority"`
	DueDate     sql.NullTime `json:"due_date"`
	ID          uint64       `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
